version: 1.0.{build}
configuration: Debug
image: Visual Studio 2017 RC
environment: 
  SolutionDir: $(APPVEYOR_BUILD_FOLDER)\ 
  matrix:
  - project_name: classroom
  - project_name: student
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
before_build:
- echo %project_name%
- dotnet restore %project_name%
build:
  verbosity: minimal